apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # echo -n 'your_root_password' | base64
  root-password: eW91cl9yb290X3Bhc3N3b3Jk
  # echo -n 'proxyuser_password' | base64
  proxy-password: cHJveHl1c2VyX3Bhc3N3b3Jk
