apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app2
  template:
    metadata:
      labels:
        app: flask-app2
    spec:
      containers:
      - name: flask-app2
        image: flask-app2:v0.2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: flask-app2-config
        - secretRef:
            name: flask-app2-secret
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20


---
apiVersion: v1
kind: Service
metadata:
  name: flask-app2-service
spec:
  selector:
    app: flask-app2
  ports:
  - port: 8082
    targetPort: 5000
  type: LoadBalancer
